### ISSUE TITLE
Field not available at ExtractArticle Page

### ISSUE THREAD

**Issue by tbrumm** [gibus/RT-Extension-RichtextCustomField#2]
Hi,
the Field is not available during ExtractArticle Page, because "html/Articles/Article/ExtractFromTicket.html" only accepts:

$CustomFields->Limit(FIELD => 'Type', OPERATOR => '=', VALUE => 'Text');
$CustomFields->Limit(FIELD => 'Type', OPERATOR => '=', VALUE => 'Wikitext');
$CustomFields->Limit(FIELD => 'Type', OPERATOR => '=', VALUE => 'Freeform');

After adding this line to the File:
$CustomFields->Limit(FIELD => 'Type', OPERATOR => '=', VALUE => 'Richtext');

you can also add this to the desired page.

There is no callback at the page, so a hint to a patch could be good.

Btw. Nice Extension

**Comment by gibus** [comment]
thanks for this report! I'll try to look at it and will add a patch (to be clean, I guess the patch would consist to add a call to callback in `html/Articles/Article/ExtractFromTicket.html` and provide this callback for Richtext CF). I'll get you update on this issue…

**Comment by gibus** [comment]
I've just push v0.05 to CPAN.

Finally, given the code in `html/Articles/Article/ExtractFromTicket.html`, and the specific feature this patch allows, the simpler and cleaner was to just add your one-line patch. I've also added a test and documentation to apply patch.

Thanks again for this improvement!
